version: '2'
services:
  opensearch:
    image: opensearchproject/opensearch:2.0.0
    container_name: opensearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/opensearch/data
    ports:
      - 127.0.0.1:9200:9200
volumes:
  esdata1:
    driver: local
